services:
  - type: web
    name: sportsplatform-be
    env: node
    rootDir: tf1-backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production